// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: clientBuf.proto

package ioBuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 对外服数据协议
type ClientBuf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 协议开关，用于一些协议级别的开关控制，比如 安全加密校验等。 : 0 不校验
	ProtocolSwitch uint32 `protobuf:"varint,1,opt,name=protocolSwitch,proto3" json:"protocolSwitch,omitempty"`
	// 业务路由（高16为主, 低16为子）
	CmdMerge uint32 `protobuf:"varint,2,opt,name=cmdMerge,proto3" json:"cmdMerge,omitempty"`
	// 业务请求数据
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ClientBuf) Reset() {
	*x = ClientBuf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientBuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBuf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBuf) ProtoMessage() {}

func (x *ClientBuf) ProtoReflect() protoreflect.Message {
	mi := &file_clientBuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBuf.ProtoReflect.Descriptor instead.
func (*ClientBuf) Descriptor() ([]byte, []int) {
	return file_clientBuf_proto_rawDescGZIP(), []int{0}
}

func (x *ClientBuf) GetProtocolSwitch() uint32 {
	if x != nil {
		return x.ProtocolSwitch
	}
	return 0
}

func (x *ClientBuf) GetCmdMerge() uint32 {
	if x != nil {
		return x.CmdMerge
	}
	return 0
}

func (x *ClientBuf) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_clientBuf_proto protoreflect.FileDescriptor

var file_clientBuf_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x69, 0x6f, 0x42, 0x75, 0x66, 0x22, 0x63, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x42, 0x75, 0x66, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6d, 0x64, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x63, 0x6d, 0x64, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x3b, 0x69, 0x6f, 0x42, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_clientBuf_proto_rawDescOnce sync.Once
	file_clientBuf_proto_rawDescData = file_clientBuf_proto_rawDesc
)

func file_clientBuf_proto_rawDescGZIP() []byte {
	file_clientBuf_proto_rawDescOnce.Do(func() {
		file_clientBuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientBuf_proto_rawDescData)
	})
	return file_clientBuf_proto_rawDescData
}

var file_clientBuf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clientBuf_proto_goTypes = []interface{}{
	(*ClientBuf)(nil), // 0: ioBuf.clientBuf
}
var file_clientBuf_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clientBuf_proto_init() }
func file_clientBuf_proto_init() {
	if File_clientBuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientBuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBuf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientBuf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clientBuf_proto_goTypes,
		DependencyIndexes: file_clientBuf_proto_depIdxs,
		MessageInfos:      file_clientBuf_proto_msgTypes,
	}.Build()
	File_clientBuf_proto = out.File
	file_clientBuf_proto_rawDesc = nil
	file_clientBuf_proto_goTypes = nil
	file_clientBuf_proto_depIdxs = nil
}
