// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: act1.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 回包
type Act1Game_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameInfo  *Act1Info `protobuf:"bytes,1,opt,name=gameInfo,proto3" json:"gameInfo,omitempty"`
	EventType uint32    `protobuf:"varint,2,opt,name=eventType,proto3" json:"eventType,omitempty"`
	EventData []uint32  `protobuf:"varint,3,rep,packed,name=eventData,proto3" json:"eventData,omitempty"`
}

func (x *Act1Game_OutObj) Reset() {
	*x = Act1Game_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_act1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Act1Game_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Act1Game_OutObj) ProtoMessage() {}

func (x *Act1Game_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_act1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Act1Game_OutObj.ProtoReflect.Descriptor instead.
func (*Act1Game_OutObj) Descriptor() ([]byte, []int) {
	return file_act1_proto_rawDescGZIP(), []int{0}
}

func (x *Act1Game_OutObj) GetGameInfo() *Act1Info {
	if x != nil {
		return x.GameInfo
	}
	return nil
}

func (x *Act1Game_OutObj) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *Act1Game_OutObj) GetEventData() []uint32 {
	if x != nil {
		return x.EventData
	}
	return nil
}

// 打牌
type PlayCard_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardIndex uint32 `protobuf:"varint,1,opt,name=cardIndex,proto3" json:"cardIndex,omitempty"`
}

func (x *PlayCard_InObj) Reset() {
	*x = PlayCard_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_act1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayCard_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayCard_InObj) ProtoMessage() {}

func (x *PlayCard_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_act1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayCard_InObj.ProtoReflect.Descriptor instead.
func (*PlayCard_InObj) Descriptor() ([]byte, []int) {
	return file_act1_proto_rawDescGZIP(), []int{1}
}

func (x *PlayCard_InObj) GetCardIndex() uint32 {
	if x != nil {
		return x.CardIndex
	}
	return 0
}

// 处理事件
type EventHandle_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChooseIndex uint32 `protobuf:"varint,1,opt,name=chooseIndex,proto3" json:"chooseIndex,omitempty"`
}

func (x *EventHandle_InObj) Reset() {
	*x = EventHandle_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_act1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventHandle_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventHandle_InObj) ProtoMessage() {}

func (x *EventHandle_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_act1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventHandle_InObj.ProtoReflect.Descriptor instead.
func (*EventHandle_InObj) Descriptor() ([]byte, []int) {
	return file_act1_proto_rawDescGZIP(), []int{2}
}

func (x *EventHandle_InObj) GetChooseIndex() uint32 {
	if x != nil {
		return x.ChooseIndex
	}
	return 0
}

// 超时提醒
type TimeOut_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqId uint32 `protobuf:"varint,1,opt,name=seqId,proto3" json:"seqId,omitempty"`
}

func (x *TimeOut_InObj) Reset() {
	*x = TimeOut_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_act1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeOut_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeOut_InObj) ProtoMessage() {}

func (x *TimeOut_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_act1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeOut_InObj.ProtoReflect.Descriptor instead.
func (*TimeOut_InObj) Descriptor() ([]byte, []int) {
	return file_act1_proto_rawDescGZIP(), []int{3}
}

func (x *TimeOut_InObj) GetSeqId() uint32 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

// 基础数据结构
type Act1Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerList     map[uint32]*Act1PlayerInfo `protobuf:"bytes,1,rep,name=playerList,proto3" json:"playerList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CurPlayerIndex uint32                     `protobuf:"varint,2,opt,name=curPlayerIndex,proto3" json:"curPlayerIndex,omitempty"`
	CardPool       []uint32                   `protobuf:"varint,3,rep,packed,name=cardPool,proto3" json:"cardPool,omitempty"`
	DiscardPool    []uint32                   `protobuf:"varint,4,rep,packed,name=discardPool,proto3" json:"discardPool,omitempty"`
	Direction      bool                       `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	BombPlayer     *Act1PlayerInfo            `protobuf:"bytes,7,opt,name=bombPlayer,proto3" json:"bombPlayer,omitempty"`
	EventPlayer    *EventPlayerInfo           `protobuf:"bytes,8,opt,name=eventPlayer,proto3" json:"eventPlayer,omitempty"`
	SeqId          uint32                     `protobuf:"varint,9,opt,name=seqId,proto3" json:"seqId,omitempty"`
	BombNum        uint32                     `protobuf:"varint,10,opt,name=bombNum,proto3" json:"bombNum,omitempty"`        // 卡池内炸弹数量
	ArrRank        []uint32                   `protobuf:"varint,11,rep,packed,name=arrRank,proto3" json:"arrRank,omitempty"` // 玩家排名
}

func (x *Act1Info) Reset() {
	*x = Act1Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_act1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Act1Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Act1Info) ProtoMessage() {}

func (x *Act1Info) ProtoReflect() protoreflect.Message {
	mi := &file_act1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Act1Info.ProtoReflect.Descriptor instead.
func (*Act1Info) Descriptor() ([]byte, []int) {
	return file_act1_proto_rawDescGZIP(), []int{4}
}

func (x *Act1Info) GetPlayerList() map[uint32]*Act1PlayerInfo {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

func (x *Act1Info) GetCurPlayerIndex() uint32 {
	if x != nil {
		return x.CurPlayerIndex
	}
	return 0
}

func (x *Act1Info) GetCardPool() []uint32 {
	if x != nil {
		return x.CardPool
	}
	return nil
}

func (x *Act1Info) GetDiscardPool() []uint32 {
	if x != nil {
		return x.DiscardPool
	}
	return nil
}

func (x *Act1Info) GetDirection() bool {
	if x != nil {
		return x.Direction
	}
	return false
}

func (x *Act1Info) GetBombPlayer() *Act1PlayerInfo {
	if x != nil {
		return x.BombPlayer
	}
	return nil
}

func (x *Act1Info) GetEventPlayer() *EventPlayerInfo {
	if x != nil {
		return x.EventPlayer
	}
	return nil
}

func (x *Act1Info) GetSeqId() uint32 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *Act1Info) GetBombNum() uint32 {
	if x != nil {
		return x.BombNum
	}
	return 0
}

func (x *Act1Info) GetArrRank() []uint32 {
	if x != nil {
		return x.ArrRank
	}
	return nil
}

type Act1PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Cards   []uint32 `protobuf:"varint,2,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	BameNum uint32   `protobuf:"varint,3,opt,name=bameNum,proto3" json:"bameNum,omitempty"`
	IsDie   bool     `protobuf:"varint,4,opt,name=isDie,proto3" json:"isDie,omitempty"`
}

func (x *Act1PlayerInfo) Reset() {
	*x = Act1PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_act1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Act1PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Act1PlayerInfo) ProtoMessage() {}

func (x *Act1PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_act1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Act1PlayerInfo.ProtoReflect.Descriptor instead.
func (*Act1PlayerInfo) Descriptor() ([]byte, []int) {
	return file_act1_proto_rawDescGZIP(), []int{5}
}

func (x *Act1PlayerInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Act1PlayerInfo) GetCards() []uint32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Act1PlayerInfo) GetBameNum() uint32 {
	if x != nil {
		return x.BameNum
	}
	return 0
}

func (x *Act1PlayerInfo) GetIsDie() bool {
	if x != nil {
		return x.IsDie
	}
	return false
}

type EventPlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerIndex uint32 `protobuf:"varint,1,opt,name=playerIndex,proto3" json:"playerIndex,omitempty"`
	EventType   uint32 `protobuf:"varint,2,opt,name=eventType,proto3" json:"eventType,omitempty"`
}

func (x *EventPlayerInfo) Reset() {
	*x = EventPlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_act1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPlayerInfo) ProtoMessage() {}

func (x *EventPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_act1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPlayerInfo.ProtoReflect.Descriptor instead.
func (*EventPlayerInfo) Descriptor() ([]byte, []int) {
	return file_act1_proto_rawDescGZIP(), []int{6}
}

func (x *EventPlayerInfo) GetPlayerIndex() uint32 {
	if x != nil {
		return x.PlayerIndex
	}
	return 0
}

func (x *EventPlayerInfo) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

// 获取游戏对局信息
type GetAct1Info_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameInfo *Act1Info `protobuf:"bytes,1,opt,name=gameInfo,proto3" json:"gameInfo,omitempty"`
}

func (x *GetAct1Info_OutObj) Reset() {
	*x = GetAct1Info_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_act1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAct1Info_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAct1Info_OutObj) ProtoMessage() {}

func (x *GetAct1Info_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_act1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAct1Info_OutObj.ProtoReflect.Descriptor instead.
func (*GetAct1Info_OutObj) Descriptor() ([]byte, []int) {
	return file_act1_proto_rawDescGZIP(), []int{7}
}

func (x *GetAct1Info_OutObj) GetGameInfo() *Act1Info {
	if x != nil {
		return x.GameInfo
	}
	return nil
}

var File_act1_proto protoreflect.FileDescriptor

var file_act1_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x63, 0x74, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70,
	0x69, 0x22, 0x78, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x31, 0x47, 0x61, 0x6d, 0x65, 0x5f, 0x4f, 0x75,
	0x74, 0x4f, 0x62, 0x6a, 0x12, 0x29, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x74,
	0x31, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2e, 0x0a, 0x0e, 0x50,
	0x6c, 0x61, 0x79, 0x43, 0x61, 0x72, 0x64, 0x5f, 0x49, 0x6e, 0x4f, 0x62, 0x6a, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x63, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x35, 0x0a, 0x11, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x49, 0x6e, 0x4f, 0x62, 0x6a,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x25, 0x0a, 0x0d, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x5f, 0x49, 0x6e,
	0x4f, 0x62, 0x6a, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x22, 0xd8, 0x03, 0x0a, 0x08, 0x61, 0x63,
	0x74, 0x31, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x63, 0x74, 0x31, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x75, 0x72, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x63,
	0x75, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x08, 0x63, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73,
	0x63, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b,
	0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x0a, 0x62, 0x6f, 0x6d,
	0x62, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x74, 0x31, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0a, 0x62, 0x6f, 0x6d, 0x62, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x36,
	0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x6f, 0x6d, 0x62, 0x4e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62,
	0x6f, 0x6d, 0x62, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x72, 0x72, 0x52, 0x61, 0x6e,
	0x6b, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x72, 0x72, 0x52, 0x61, 0x6e, 0x6b,
	0x1a, 0x52, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x74, 0x31, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x68, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x31, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x62, 0x61, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x62, 0x61, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x44, 0x69,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x44, 0x69, 0x65, 0x22, 0x51,
	0x0a, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x3f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x31, 0x49, 0x6e, 0x66, 0x6f,
	0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x29, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x63, 0x74, 0x31, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_act1_proto_rawDescOnce sync.Once
	file_act1_proto_rawDescData = file_act1_proto_rawDesc
)

func file_act1_proto_rawDescGZIP() []byte {
	file_act1_proto_rawDescOnce.Do(func() {
		file_act1_proto_rawDescData = protoimpl.X.CompressGZIP(file_act1_proto_rawDescData)
	})
	return file_act1_proto_rawDescData
}

var file_act1_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_act1_proto_goTypes = []interface{}{
	(*Act1Game_OutObj)(nil),    // 0: api.Act1Game_OutObj
	(*PlayCard_InObj)(nil),     // 1: api.PlayCard_InObj
	(*EventHandle_InObj)(nil),  // 2: api.EventHandle_InObj
	(*TimeOut_InObj)(nil),      // 3: api.TimeOut_InObj
	(*Act1Info)(nil),           // 4: api.act1Info
	(*Act1PlayerInfo)(nil),     // 5: api.act1PlayerInfo
	(*EventPlayerInfo)(nil),    // 6: api.eventPlayerInfo
	(*GetAct1Info_OutObj)(nil), // 7: api.GetAct1Info_OutObj
	nil,                        // 8: api.act1Info.PlayerListEntry
}
var file_act1_proto_depIdxs = []int32{
	4, // 0: api.Act1Game_OutObj.gameInfo:type_name -> api.act1Info
	8, // 1: api.act1Info.playerList:type_name -> api.act1Info.PlayerListEntry
	5, // 2: api.act1Info.bombPlayer:type_name -> api.act1PlayerInfo
	6, // 3: api.act1Info.eventPlayer:type_name -> api.eventPlayerInfo
	4, // 4: api.GetAct1Info_OutObj.gameInfo:type_name -> api.act1Info
	5, // 5: api.act1Info.PlayerListEntry.value:type_name -> api.act1PlayerInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_act1_proto_init() }
func file_act1_proto_init() {
	if File_act1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_act1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Act1Game_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_act1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayCard_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_act1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventHandle_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_act1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeOut_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_act1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Act1Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_act1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Act1PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_act1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventPlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_act1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAct1Info_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_act1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_act1_proto_goTypes,
		DependencyIndexes: file_act1_proto_depIdxs,
		MessageInfos:      file_act1_proto_msgTypes,
	}.Build()
	File_act1_proto = out.File
	file_act1_proto_rawDesc = nil
	file_act1_proto_goTypes = nil
	file_act1_proto_depIdxs = nil
}
