// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: gameNet.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取游戏服务器网关
type GetGateWay_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId uint64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *GetGateWay_InObj) Reset() {
	*x = GetGateWay_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameNet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGateWay_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGateWay_InObj) ProtoMessage() {}

func (x *GetGateWay_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_gameNet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGateWay_InObj.ProtoReflect.Descriptor instead.
func (*GetGateWay_InObj) Descriptor() ([]byte, []int) {
	return file_gameNet_proto_rawDescGZIP(), []int{0}
}

func (x *GetGateWay_InObj) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type GetGateWay_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *GetGateWay_OutObj) Reset() {
	*x = GetGateWay_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameNet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGateWay_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGateWay_OutObj) ProtoMessage() {}

func (x *GetGateWay_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_gameNet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGateWay_OutObj.ProtoReflect.Descriptor instead.
func (*GetGateWay_OutObj) Descriptor() ([]byte, []int) {
	return file_gameNet_proto_rawDescGZIP(), []int{1}
}

func (x *GetGateWay_OutObj) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetGateWay_OutObj) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

// 连接游戏服务器
type ConGlobalObjInit_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomId uint64 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *ConGlobalObjInit_InObj) Reset() {
	*x = ConGlobalObjInit_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameNet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConGlobalObjInit_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConGlobalObjInit_InObj) ProtoMessage() {}

func (x *ConGlobalObjInit_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_gameNet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConGlobalObjInit_InObj.ProtoReflect.Descriptor instead.
func (*ConGlobalObjInit_InObj) Descriptor() ([]byte, []int) {
	return file_gameNet_proto_rawDescGZIP(), []int{2}
}

func (x *ConGlobalObjInit_InObj) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ConGlobalObjInit_InObj) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type ConGlobalObjInit_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ConGlobalObjInit_OutObj) Reset() {
	*x = ConGlobalObjInit_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameNet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConGlobalObjInit_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConGlobalObjInit_OutObj) ProtoMessage() {}

func (x *ConGlobalObjInit_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_gameNet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConGlobalObjInit_OutObj.ProtoReflect.Descriptor instead.
func (*ConGlobalObjInit_OutObj) Descriptor() ([]byte, []int) {
	return file_gameNet_proto_rawDescGZIP(), []int{3}
}

func (x *ConGlobalObjInit_OutObj) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_gameNet_proto protoreflect.FileDescriptor

var file_gameNet_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x22, 0x2a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x61, 0x74, 0x65, 0x57,
	0x61, 0x79, 0x5f, 0x49, 0x6e, 0x4f, 0x62, 0x6a, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x22, 0x3b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x61, 0x74, 0x65, 0x57, 0x61, 0x79, 0x5f, 0x4f,
	0x75, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x42, 0x0a,
	0x16, 0x43, 0x6f, 0x6e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4f, 0x62, 0x6a, 0x49, 0x6e, 0x69,
	0x74, 0x5f, 0x49, 0x6e, 0x4f, 0x62, 0x6a, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x22, 0x29, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4f, 0x62,
	0x6a, 0x49, 0x6e, 0x69, 0x74, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gameNet_proto_rawDescOnce sync.Once
	file_gameNet_proto_rawDescData = file_gameNet_proto_rawDesc
)

func file_gameNet_proto_rawDescGZIP() []byte {
	file_gameNet_proto_rawDescOnce.Do(func() {
		file_gameNet_proto_rawDescData = protoimpl.X.CompressGZIP(file_gameNet_proto_rawDescData)
	})
	return file_gameNet_proto_rawDescData
}

var file_gameNet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gameNet_proto_goTypes = []interface{}{
	(*GetGateWay_InObj)(nil),        // 0: api.GetGateWay_InObj
	(*GetGateWay_OutObj)(nil),       // 1: api.GetGateWay_OutObj
	(*ConGlobalObjInit_InObj)(nil),  // 2: api.ConGlobalObjInit_InObj
	(*ConGlobalObjInit_OutObj)(nil), // 3: api.ConGlobalObjInit_OutObj
}
var file_gameNet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gameNet_proto_init() }
func file_gameNet_proto_init() {
	if File_gameNet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gameNet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGateWay_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameNet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGateWay_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameNet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConGlobalObjInit_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameNet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConGlobalObjInit_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gameNet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gameNet_proto_goTypes,
		DependencyIndexes: file_gameNet_proto_depIdxs,
		MessageInfos:      file_gameNet_proto_msgTypes,
	}.Build()
	File_gameNet_proto = out.File
	file_gameNet_proto_rawDesc = nil
	file_gameNet_proto_goTypes = nil
	file_gameNet_proto_depIdxs = nil
}
