// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: room.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 房间是否存在
type IsRoomExist_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId uint64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *IsRoomExist_InObj) Reset() {
	*x = IsRoomExist_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsRoomExist_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsRoomExist_InObj) ProtoMessage() {}

func (x *IsRoomExist_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsRoomExist_InObj.ProtoReflect.Descriptor instead.
func (*IsRoomExist_InObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (x *IsRoomExist_InObj) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type IsRoomExist_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *IsRoomExist_OutObj) Reset() {
	*x = IsRoomExist_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsRoomExist_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsRoomExist_OutObj) ProtoMessage() {}

func (x *IsRoomExist_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsRoomExist_OutObj.ProtoReflect.Descriptor instead.
func (*IsRoomExist_OutObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *IsRoomExist_OutObj) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 创建房间
type CreateRoom_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId uint64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	ActId  uint32 `protobuf:"varint,2,opt,name=actId,proto3" json:"actId,omitempty"`
	GameLv uint32 `protobuf:"varint,3,opt,name=gameLv,proto3" json:"gameLv,omitempty"`
}

func (x *CreateRoom_InObj) Reset() {
	*x = CreateRoom_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoom_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoom_InObj) ProtoMessage() {}

func (x *CreateRoom_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoom_InObj.ProtoReflect.Descriptor instead.
func (*CreateRoom_InObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoom_InObj) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateRoom_InObj) GetActId() uint32 {
	if x != nil {
		return x.ActId
	}
	return 0
}

func (x *CreateRoom_InObj) GetGameLv() uint32 {
	if x != nil {
		return x.GameLv
	}
	return 0
}

type CreateRoom_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players map[uint32]*PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //房间内的玩家uid,准备情况
}

func (x *CreateRoom_OutObj) Reset() {
	*x = CreateRoom_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoom_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoom_OutObj) ProtoMessage() {}

func (x *CreateRoom_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoom_OutObj.ProtoReflect.Descriptor instead.
func (*CreateRoom_OutObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoom_OutObj) GetPlayers() map[uint32]*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

// 加入房间
type JoinRoom_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId uint64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *JoinRoom_InObj) Reset() {
	*x = JoinRoom_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoom_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom_InObj) ProtoMessage() {}

func (x *JoinRoom_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom_InObj.ProtoReflect.Descriptor instead.
func (*JoinRoom_InObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRoom_InObj) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type JoinRoom_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players map[uint32]*PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //游戏位次=>玩家信息情况
}

func (x *JoinRoom_OutObj) Reset() {
	*x = JoinRoom_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoom_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom_OutObj) ProtoMessage() {}

func (x *JoinRoom_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom_OutObj.ProtoReflect.Descriptor instead.
func (*JoinRoom_OutObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoom_OutObj) GetPlayers() map[uint32]*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

// 加入游戏
type JoinGame_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostionId uint32 `protobuf:"varint,1,opt,name=postionId,proto3" json:"postionId,omitempty"`
}

func (x *JoinGame_InObj) Reset() {
	*x = JoinGame_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGame_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGame_InObj) ProtoMessage() {}

func (x *JoinGame_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGame_InObj.ProtoReflect.Descriptor instead.
func (*JoinGame_InObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{6}
}

func (x *JoinGame_InObj) GetPostionId() uint32 {
	if x != nil {
		return x.PostionId
	}
	return 0
}

type JoinGame_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players map[uint32]*PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //游戏位次=>玩家信息情况
}

func (x *JoinGame_OutObj) Reset() {
	*x = JoinGame_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGame_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGame_OutObj) ProtoMessage() {}

func (x *JoinGame_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGame_OutObj.ProtoReflect.Descriptor instead.
func (*JoinGame_OutObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{7}
}

func (x *JoinGame_OutObj) GetPlayers() map[uint32]*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	State    bool   `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	IsMaster bool   `protobuf:"varint,3,opt,name=isMaster,proto3" json:"isMaster,omitempty"`
	Head     string `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
	Name     string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	IsRobot  bool   `protobuf:"varint,6,opt,name=isRobot,proto3" json:"isRobot,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInfo) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *PlayerInfo) GetIsMaster() bool {
	if x != nil {
		return x.IsMaster
	}
	return false
}

func (x *PlayerInfo) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetIsRobot() bool {
	if x != nil {
		return x.IsRobot
	}
	return false
}

// 更改游戏位次
type ChangePos_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewPosId uint32 `protobuf:"varint,1,opt,name=newPosId,proto3" json:"newPosId,omitempty"`
}

func (x *ChangePos_InObj) Reset() {
	*x = ChangePos_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePos_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePos_InObj) ProtoMessage() {}

func (x *ChangePos_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePos_InObj.ProtoReflect.Descriptor instead.
func (*ChangePos_InObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{9}
}

func (x *ChangePos_InObj) GetNewPosId() uint32 {
	if x != nil {
		return x.NewPosId
	}
	return 0
}

type ChangePos_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players map[uint32]*PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //游戏位次=>玩家信息情况
}

func (x *ChangePos_OutObj) Reset() {
	*x = ChangePos_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePos_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePos_OutObj) ProtoMessage() {}

func (x *ChangePos_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePos_OutObj.ProtoReflect.Descriptor instead.
func (*ChangePos_OutObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{10}
}

func (x *ChangePos_OutObj) GetPlayers() map[uint32]*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type LeaveGame_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players map[uint32]*PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //游戏位次=>玩家信息情况
}

func (x *LeaveGame_OutObj) Reset() {
	*x = LeaveGame_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveGame_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGame_OutObj) ProtoMessage() {}

func (x *LeaveGame_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGame_OutObj.ProtoReflect.Descriptor instead.
func (*LeaveGame_OutObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{11}
}

func (x *LeaveGame_OutObj) GetPlayers() map[uint32]*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type SetOrCancelPrepare_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players map[uint32]*PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //游戏位次=>玩家信息情况
}

func (x *SetOrCancelPrepare_OutObj) Reset() {
	*x = SetOrCancelPrepare_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOrCancelPrepare_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrCancelPrepare_OutObj) ProtoMessage() {}

func (x *SetOrCancelPrepare_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrCancelPrepare_OutObj.ProtoReflect.Descriptor instead.
func (*SetOrCancelPrepare_OutObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{12}
}

func (x *SetOrCancelPrepare_OutObj) GetPlayers() map[uint32]*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type GameStart_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *GameStart_OutObj) Reset() {
	*x = GameStart_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStart_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStart_OutObj) ProtoMessage() {}

func (x *GameStart_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStart_OutObj.ProtoReflect.Descriptor instead.
func (*GameStart_OutObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{13}
}

func (x *GameStart_OutObj) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 添加机器人
type AddRobot_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotHead string `protobuf:"bytes,1,opt,name=robotHead,proto3" json:"robotHead,omitempty"`
	RobotName string `protobuf:"bytes,2,opt,name=robotName,proto3" json:"robotName,omitempty"`
}

func (x *AddRobot_InObj) Reset() {
	*x = AddRobot_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRobot_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRobot_InObj) ProtoMessage() {}

func (x *AddRobot_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRobot_InObj.ProtoReflect.Descriptor instead.
func (*AddRobot_InObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{14}
}

func (x *AddRobot_InObj) GetRobotHead() string {
	if x != nil {
		return x.RobotHead
	}
	return ""
}

func (x *AddRobot_InObj) GetRobotName() string {
	if x != nil {
		return x.RobotName
	}
	return ""
}

type AddRobot_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players map[uint32]*PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //游戏位次=>玩家信息情况
}

func (x *AddRobot_OutObj) Reset() {
	*x = AddRobot_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRobot_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRobot_OutObj) ProtoMessage() {}

func (x *AddRobot_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRobot_OutObj.ProtoReflect.Descriptor instead.
func (*AddRobot_OutObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{15}
}

func (x *AddRobot_OutObj) GetPlayers() map[uint32]*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

// 删除机器人
type DelRobot_InObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PosId uint32 `protobuf:"varint,1,opt,name=posId,proto3" json:"posId,omitempty"`
}

func (x *DelRobot_InObj) Reset() {
	*x = DelRobot_InObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRobot_InObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRobot_InObj) ProtoMessage() {}

func (x *DelRobot_InObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRobot_InObj.ProtoReflect.Descriptor instead.
func (*DelRobot_InObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{16}
}

func (x *DelRobot_InObj) GetPosId() uint32 {
	if x != nil {
		return x.PosId
	}
	return 0
}

type DelRobot_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players map[uint32]*PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //游戏位次=>玩家信息情况
}

func (x *DelRobot_OutObj) Reset() {
	*x = DelRobot_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRobot_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRobot_OutObj) ProtoMessage() {}

func (x *DelRobot_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRobot_OutObj.ProtoReflect.Descriptor instead.
func (*DelRobot_OutObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{17}
}

func (x *DelRobot_OutObj) GetPlayers() map[uint32]*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type GetRoomInfo_OutObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players map[uint32]*PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //游戏位次=>玩家信息情况
}

func (x *GetRoomInfo_OutObj) Reset() {
	*x = GetRoomInfo_OutObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomInfo_OutObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfo_OutObj) ProtoMessage() {}

func (x *GetRoomInfo_OutObj) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfo_OutObj.ProtoReflect.Descriptor instead.
func (*GetRoomInfo_OutObj) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{18}
}

func (x *GetRoomInfo_OutObj) GetPlayers() map[uint32]*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_room_proto protoreflect.FileDescriptor

var file_room_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70,
	0x69, 0x22, 0x2b, 0x0a, 0x11, 0x49, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x5f, 0x49, 0x6e, 0x4f, 0x62, 0x6a, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x24,
	0x0a, 0x12, 0x49, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x78, 0x69, 0x73, 0x74, 0x5f, 0x4f, 0x75,
	0x74, 0x4f, 0x62, 0x6a, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x22, 0x58, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x5f, 0x49, 0x6e, 0x4f, 0x62, 0x6a, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x4c, 0x76,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x4c, 0x76, 0x22, 0x9f,
	0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x4f, 0x75,
	0x74, 0x4f, 0x62, 0x6a, 0x12, 0x3d, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x1a, 0x4b, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x28, 0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x49, 0x6e, 0x4f,
	0x62, 0x6a, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x0f, 0x4a,
	0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x3b,
	0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x5f, 0x4f,
	0x75, 0x74, 0x4f, 0x62, 0x6a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x1a, 0x4b, 0x0a, 0x0c, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2e, 0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x5f, 0x49, 0x6e, 0x4f, 0x62, 0x6a, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70,
	0x6f, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x0f, 0x4a, 0x6f, 0x69,
	0x6e, 0x47, 0x61, 0x6d, 0x65, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x3b, 0x0a, 0x07,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x5f, 0x4f, 0x75, 0x74,
	0x4f, 0x62, 0x6a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x1a, 0x4b, 0x0a, 0x0c, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x92, 0x01, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x73, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x22, 0x2d, 0x0a, 0x0f, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x5f, 0x49, 0x6e, 0x4f, 0x62, 0x6a, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x65, 0x77, 0x50, 0x6f, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x6e, 0x65, 0x77, 0x50, 0x6f, 0x73, 0x49, 0x64, 0x22, 0x9d, 0x01, 0x0a, 0x10, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x12,
	0x3c, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x6f, 0x73,
	0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x1a, 0x4b, 0x0a,
	0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x9d, 0x01, 0x0a, 0x10, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x12,
	0x3c, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x1a, 0x4b, 0x0a,
	0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xaf, 0x01, 0x0a, 0x19, 0x53,
	0x65, 0x74, 0x4f, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x45, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x65, 0x74, 0x4f, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x1a,
	0x4b, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x22, 0x0a, 0x10,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x22, 0x4c, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x49, 0x6e, 0x4f,
	0x62, 0x6a, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x48, 0x65, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x9b,
	0x01, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x4f, 0x75, 0x74, 0x4f,
	0x62, 0x6a, 0x12, 0x3b, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x1a,
	0x4b, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x26, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x49, 0x6e, 0x4f, 0x62, 0x6a, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x6f, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70,
	0x6f, 0x73, 0x49, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x3b, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x44, 0x65, 0x6c, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x1a, 0x4b, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0xa1, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e,
	0x66, 0x6f, 0x5f, 0x4f, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x12, 0x3e, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x4f, 0x75, 0x74,
	0x4f, 0x62, 0x6a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x1a, 0x4b, 0x0a, 0x0c, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData = file_room_proto_rawDesc
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_proto_rawDescData)
	})
	return file_room_proto_rawDescData
}

var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_room_proto_goTypes = []interface{}{
	(*IsRoomExist_InObj)(nil),         // 0: api.IsRoomExist_InObj
	(*IsRoomExist_OutObj)(nil),        // 1: api.IsRoomExist_OutObj
	(*CreateRoom_InObj)(nil),          // 2: api.CreateRoom_InObj
	(*CreateRoom_OutObj)(nil),         // 3: api.CreateRoom_OutObj
	(*JoinRoom_InObj)(nil),            // 4: api.JoinRoom_InObj
	(*JoinRoom_OutObj)(nil),           // 5: api.JoinRoom_OutObj
	(*JoinGame_InObj)(nil),            // 6: api.JoinGame_InObj
	(*JoinGame_OutObj)(nil),           // 7: api.JoinGame_OutObj
	(*PlayerInfo)(nil),                // 8: api.playerInfo
	(*ChangePos_InObj)(nil),           // 9: api.ChangePos_InObj
	(*ChangePos_OutObj)(nil),          // 10: api.ChangePos_OutObj
	(*LeaveGame_OutObj)(nil),          // 11: api.LeaveGame_OutObj
	(*SetOrCancelPrepare_OutObj)(nil), // 12: api.SetOrCancelPrepare_OutObj
	(*GameStart_OutObj)(nil),          // 13: api.GameStart_OutObj
	(*AddRobot_InObj)(nil),            // 14: api.AddRobot_InObj
	(*AddRobot_OutObj)(nil),           // 15: api.AddRobot_OutObj
	(*DelRobot_InObj)(nil),            // 16: api.DelRobot_InObj
	(*DelRobot_OutObj)(nil),           // 17: api.DelRobot_OutObj
	(*GetRoomInfo_OutObj)(nil),        // 18: api.GetRoomInfo_OutObj
	nil,                               // 19: api.CreateRoom_OutObj.PlayersEntry
	nil,                               // 20: api.JoinRoom_OutObj.PlayersEntry
	nil,                               // 21: api.JoinGame_OutObj.PlayersEntry
	nil,                               // 22: api.ChangePos_OutObj.PlayersEntry
	nil,                               // 23: api.LeaveGame_OutObj.PlayersEntry
	nil,                               // 24: api.SetOrCancelPrepare_OutObj.PlayersEntry
	nil,                               // 25: api.AddRobot_OutObj.PlayersEntry
	nil,                               // 26: api.DelRobot_OutObj.PlayersEntry
	nil,                               // 27: api.GetRoomInfo_OutObj.PlayersEntry
}
var file_room_proto_depIdxs = []int32{
	19, // 0: api.CreateRoom_OutObj.players:type_name -> api.CreateRoom_OutObj.PlayersEntry
	20, // 1: api.JoinRoom_OutObj.players:type_name -> api.JoinRoom_OutObj.PlayersEntry
	21, // 2: api.JoinGame_OutObj.players:type_name -> api.JoinGame_OutObj.PlayersEntry
	22, // 3: api.ChangePos_OutObj.players:type_name -> api.ChangePos_OutObj.PlayersEntry
	23, // 4: api.LeaveGame_OutObj.players:type_name -> api.LeaveGame_OutObj.PlayersEntry
	24, // 5: api.SetOrCancelPrepare_OutObj.players:type_name -> api.SetOrCancelPrepare_OutObj.PlayersEntry
	25, // 6: api.AddRobot_OutObj.players:type_name -> api.AddRobot_OutObj.PlayersEntry
	26, // 7: api.DelRobot_OutObj.players:type_name -> api.DelRobot_OutObj.PlayersEntry
	27, // 8: api.GetRoomInfo_OutObj.players:type_name -> api.GetRoomInfo_OutObj.PlayersEntry
	8,  // 9: api.CreateRoom_OutObj.PlayersEntry.value:type_name -> api.playerInfo
	8,  // 10: api.JoinRoom_OutObj.PlayersEntry.value:type_name -> api.playerInfo
	8,  // 11: api.JoinGame_OutObj.PlayersEntry.value:type_name -> api.playerInfo
	8,  // 12: api.ChangePos_OutObj.PlayersEntry.value:type_name -> api.playerInfo
	8,  // 13: api.LeaveGame_OutObj.PlayersEntry.value:type_name -> api.playerInfo
	8,  // 14: api.SetOrCancelPrepare_OutObj.PlayersEntry.value:type_name -> api.playerInfo
	8,  // 15: api.AddRobot_OutObj.PlayersEntry.value:type_name -> api.playerInfo
	8,  // 16: api.DelRobot_OutObj.PlayersEntry.value:type_name -> api.playerInfo
	8,  // 17: api.GetRoomInfo_OutObj.PlayersEntry.value:type_name -> api.playerInfo
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsRoomExist_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsRoomExist_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoom_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoom_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoom_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoom_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGame_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGame_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangePos_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangePos_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveGame_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOrCancelPrepare_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStart_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRobot_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRobot_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRobot_InObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRobot_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomInfo_OutObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_rawDesc = nil
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
