package common

// 错误码
const (
	ERR_NO_GATEWAY          = 1
	ERR_NO_GATEWAY_PORT     = 2
	ERR_ETCD_GET_PORT       = 3
	ERR_NO_CONNECT_EXIST    = 3
	ERR_NO_ROOMID_EXIST     = 4
	ERR_IS_NOT_ROOM_MASATER = 5
	ERR_IS_ALREADY_IN_ROOM  = 6
	ERR_IS_NOT_IN_ROOM      = 7
	ERR_IS_NO_PREPARE_EXIST = 8

	ERR_REDIS_WRITE_ERROR = 10000
	ERR_REDIS_QUERY       = 10001
)
